[package]
name = "websocket-implementation"
version = "0.1.0"
authors = ["bjorklund.bruce@gmail.com"]
edition = "2018"

[dependencies]
log = "0.4.14"
env_logger = "0.8.2"
input_buffer = "0.4.0"
http = "0.2"
bytes = "1.0"
thiserror = "1.0.23"